//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalariaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health_Admin
    {
        public int Health_Admin_ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Contact_Number { get; set; }
        public string Health_Admin_Number { get; set; }
        public string Password { get; set; }
    }
}
