//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalariaAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MalariaEntities1 : DbContext
    {
        public MalariaEntities1()
            : base("name=MalariaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cause> Causes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Health_Admin> Health_Admin { get; set; }
        public virtual DbSet<Infection_Cycle> Infection_Cycle { get; set; }
        public virtual DbSet<Malaria> Malarias { get; set; }
        public virtual DbSet<Malaria_Type> Malaria_Type { get; set; }
        public virtual DbSet<Preventative_Measure> Preventative_Measure { get; set; }
        public virtual DbSet<Quick_Fact> Quick_Fact { get; set; }
        public virtual DbSet<Risk> Risks { get; set; }
        public virtual DbSet<Symptom> Symptoms { get; set; }
        public virtual DbSet<Vaccination> Vaccinations { get; set; }
    }
}
