//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalariaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quick_Fact
    {
        public int Quick_Fact_ID { get; set; }
        public string Fact { get; set; }
        public Nullable<int> Malaria_ID { get; set; }
    
        public virtual Malaria Malaria { get; set; }
 //       public object Quick_Fact { get; internal set; }
    }
}
